// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQNSAJE4Yas_dot2zHTD4MJRm29ZTPS1A',
    appId: '1:769959016551:web:f5e1315376d167020e7cc2',
    messagingSenderId: '769959016551',
    projectId: 'applicationcli',
    authDomain: 'applicationcli.firebaseapp.com',
    storageBucket: 'applicationcli.firebasestorage.app',
    measurementId: 'G-ZL5EFD069K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtNFnDp_Mly5XqiKjTqDhfsKN2b2dFRss',
    appId: '1:769959016551:android:fbc4f472337920970e7cc2',
    messagingSenderId: '769959016551',
    projectId: 'applicationcli',
    storageBucket: 'applicationcli.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZJXZlYYPy1Sr3ZNSX0ocT_k8SkonhSKs',
    appId: '1:769959016551:ios:d11eb0b9ad5632570e7cc2',
    messagingSenderId: '769959016551',
    projectId: 'applicationcli',
    storageBucket: 'applicationcli.firebasestorage.app',
    iosClientId: '769959016551-r17ksgh4kpu34jgrk4dbag4rr51pi0nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZJXZlYYPy1Sr3ZNSX0ocT_k8SkonhSKs',
    appId: '1:769959016551:ios:d11eb0b9ad5632570e7cc2',
    messagingSenderId: '769959016551',
    projectId: 'applicationcli',
    storageBucket: 'applicationcli.firebasestorage.app',
    iosClientId: '769959016551-r17ksgh4kpu34jgrk4dbag4rr51pi0nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationCli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQNSAJE4Yas_dot2zHTD4MJRm29ZTPS1A',
    appId: '1:769959016551:web:347ef2c6def8c90f0e7cc2',
    messagingSenderId: '769959016551',
    projectId: 'applicationcli',
    authDomain: 'applicationcli.firebaseapp.com',
    storageBucket: 'applicationcli.firebasestorage.app',
    measurementId: 'G-Q56QBXGXEJ',
  );

}